DROP TABLE IF EXISTS game;

CREATE TABLE IF NOT EXISTS game (
    id serial primary key,
    game_date date,
    game_num text,
    dow text,
    visitor_name text,
    visitor_league text,
    visitor_game_num text,
    home_name text,
    home_league text,
    home_game_num text,
    visitor_score integer,
    home_score integer,
    game_len_outs integer,
    day_night text, -- should be enum
    completion_info text,
    forfeit_info text,
    protest_info text,
    park_id text,
    attendance integer,
    game_time integer,
    visitor_line_score text,
    home_line_score text,

    --visitor offensive
    visitor_at_bats integer,
    visitor_hits integer,
    visitor_doubles integer,
    visitor_triples integer,
    visitor_home_runs integer,
    visitor_rbi integer,
    visitor_sacrifice_hits integer,
    visitor_sacrifice_flies integer,
    visitor_hit_by_pitch integer,
    visitor_walks  integer,
    visitor_intentional_walks integer,
    visitor_strikeouts integer,
    visitor_stolen_bases integer,
    visitor_caught_stealing integer,
    visitor_grounded_into_double_plays integer,
    visitor_awarded_first_on_catcher_interference integer,
    visitor_left_on_base integer,

    --visitor team pitching
    visitor_pitches_used integer,
    visitor_individual_earned_runs integer,
    visitor_team_earned_runs integer,
    visitor_wild_pitches integer,
    visitor_balks integer,

    -- visitor defensive
    visitor_putouts integer,
    visitor_assists integer,
    visitor_errors integer,
    visitor_passed_balls integer,
    visitor_double_plays integer,
    visitor_triple_plays integer,

      -- home offensive
    home_at_bats integer,
    home_hits integer,
    home_doubles integer,
    home_triples integer,
    home_home_runs integer,
    home_rbi integer,
    home_sacrifice_hits integer,
    home_sacrifice_flies integer,
    home_hit_by_pitch integer,
    home_walks  integer,
    home_intentional_walks integer,
    home_strikeouts integer,
    home_stolen_bases integer,
    home_caught_stealing integer,
    home_grounded_into_double_plays integer,
    home_awarded_first_on_catcher_interference integer,
    home_left_on_base integer,

    --home team pitching
    home_pitches_used integer,
    home_individual_earned_runs integer,
    home_team_earned_runs integer,
    home_wild_pitches integer,
    home_balks integer,

    -- home defensive
    home_putouts integer,
    home_assists integer,
    home_errors integer,
    home_passed_balls integer,
    home_double_plays integer,
    home_triple_plays integer,

    ump_hp_id text,
    ump_hp_name text,
    ump_1b_id text,
    ump_1b_name text,
    ump_2b_id text,
    ump_2b_name text,
    ump_3b_id text,
    ump_3b_name text,
    ump_lf_id text,
    ump_lf_name text,
    ump_rf_id text,
    ump_rf_name text,

    visitor_mgr_id text,
    visitor_mgr_name text,
    home_mgr_id text,
    home_mgr_name text,
    winning_pitcher_id text,
    winning_pitcher_name text,
    losing_pitcher_id text,
    losing_pitcher_name text,
    saving_pitcher_id text,
    saving_pitcher_name text,
    game_winning_rbi_batter_id text,
    game_winning_rbi_batter_name text,
    visitor_starting_pitcher_id text,
    visitor_starting_pitcher_name text,
    home_starting_pitcher_id text,
    home_starting_pitcher_name text,
    visitor_pos_1_id text,
    visitor_pos_1_name text,
    visitor_pos_1_def_pos text,
    visitor_pos_2_id text,
    visitor_pos_2_name text,
    visitor_pos_2_def_pos text,
    visitor_pos_3_id text,
    visitor_pos_3_name text,
    visitor_pos_3_def_pos text,
    visitor_pos_4_id text,
    visitor_pos_4_name text,
    visitor_pos_4_def_pos text,
    visitor_pos_5_id text,
    visitor_pos_5_name text,
    visitor_pos_5_def_pos text,
    visitor_pos_6_id text,
    visitor_pos_6_name text,
    visitor_pos_6_def_pos text,
    visitor_pos_7_id text,
    visitor_pos_7_name text,
    visitor_pos_7_def_pos text,
    visitor_pos_8_id text,
    visitor_pos_8_name text,
    visitor_pos_8_def_pos text,
    visitor_pos_9_id text,
    visitor_pos_9_name text,
    visitor_pos_9_def_pos text,
    home_pos_1_id text,
    home_pos_1_name text,
    home_pos_1_def_pos text,
    home_pos_2_id text,
    home_pos_2_name text,
    home_pos_2_def_pos text,
    home_pos_3_id text,
    home_pos_3_name text,
    home_pos_3_def_pos text,
    home_pos_4_id text,
    home_pos_4_name text,
    home_pos_4_def_pos text,
    home_pos_5_id text,
    home_pos_5_name text,
    home_pos_5_def_pos text,
    home_pos_6_id text,
    home_pos_6_name text,
    home_pos_6_def_pos text,
    home_pos_7_id text,
    home_pos_7_name text,
    home_pos_7_def_pos text,
    home_pos_8_id text,
    home_pos_8_name text,
    home_pos_8_def_pos text,
    home_pos_9_id text,
    home_pos_9_name text,
    home_pos_9_def_pos text,
    addition_info text,
    acquisition_type text -- could be enum
);

COMMENT ON TABLE game IS 'See https://www.retrosheet.org/gamelogs/glfields.txt for a detailed description of fields.';